### ISSUE TITLE
java imports

### ISSUE THREAD

**Issue by matosimi** [epi/asap#1]
Hi,

I'm trying to use asap2wav inside my java project, but dunno where can I find these:

import net.sf.asap.ASAP;
import net.sf.asap.ASAPInfo;
import net.sf.asap.ASAPSampleFormat;

Could you help me out?

thanks
MatoSimi
http://matosimi.atari.org

**Comment by pfusik** [comment]
Only now I found this ticket. :) You should have reported it as described at https://asap.sourceforge.net/contact.html

There are `asap2wav.jar` and `asap.jar`. Do you still need them?

**Comment by matosimi** [comment]
It's from 9 years ago, i don't remember what i was trying... Just close it :)
